sudo: required
language: node_js
node_js:
  - "6"
services:
  - docker

branches:
  only:
    - master

notifications:
  email:
    - dev@joeir.net

stages:
  - test
  - publish

jobs:
  include:
    - stage: test
      before_script:
        - CC_TEST_REPORTER_ID="${CC_TOKEN}"
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - set -e
        - docker-compose -f ./provisioning/test.docker-compose.yml build mocha_test
        - docker-compose -f ./provisioning/test.docker-compose.yml run mocha_test
      after_script:
        - ./cc-test-reporter after-build -r "${CC_TOKEN}" --coverage-input-type lcov --exit-code ${TRAVIS_TEST_RESULT}
    - stage: test
      script:
        - set -e
        - docker-compose -f ./provisioning/test.docker-compose.yml build es_lint
        - docker-compose -f ./provisioning/test.docker-compose.yml run es_lint
    - stage: publish
      script:
        - set -e
        - git checkout ${TRAVIS_BRANCH};
        - COMMIT_MESSAGE=$(git log -n 1 --pretty=format:"%B");
        - |
          if [[ $COMMIT_MESSAGE == *"[minor version bump]"* ]]; then
            ${CURR_DIR}/../versioning/iterate major -i -q;
          elif [[ $COMMIT_MESSAGE == *"[minor version bump]"* ]]; then
            ${CURR_DIR}/../versioning/iterate minor -i -q;
          else
            ${CURR_DIR}/../versioning/iterate -i -q;
          fi;
        - git push -q https://zephinzer:${GH_TOKEN}@github.com/zephinzer/anna.git --tags;
        - docker login -u "${DH_USERNAME}" -p "${DH_PASSWORD}"
        - CURRENT_VERSION=$(./scripts/versioning/get-latest -q)
        - TAG_LATEST="zephinzer/anna:latest"
        - TAG_VERSION="zephinzer/anna:${CURRENT_VERSION}"
        - npm run build -- development
        - docker push ${TAG_LATEST}-dev
        - docker tag ${TAG_LATEST}-dev ${TAG_VERSION}-dev
        - docker push ${TAG_VERSION}-dev
        - npm run build -- production
        - docker push ${TAG_LATEST}
        - docker tag ${TAG_LATEST} ${TAG_VERSION}
        - docker push ${TAG_VERSION}
        - docker logout
        # - |
        #   if [[ $COMMIT_MESSAGE == *"[force build]"* ]]; then
        #     ${CURR_DIR}/../versioning/iterate minor -i -q;
        #   else
        #     ${CURR_DIR}/../versioning/iterate -i -q;
        #   fi;
        # - git push -q https://zephinzer:${GITHUB_TOKEN}@github.com/zephinzer/docker-image-alpine-node.git --tags;
        # - git checkout -b release;
        # - git rebase ${TRAVIS_BRANCH};
        # - git push -q https://zephinzer:${GITHUB_TOKEN}@github.com/zephinzer/docker-image-alpine-node.git --tags;