sudo: required
language: node_js
node_js:
  - "6"
services:
  - docker

branches:
  only:
    - master

notifications:
  email:
    - dev@joeir.net

stages:
  - test
  - release
  - publish

jobs:
  include:
    - stage: test
      env:
        - LABEL: eslint
      script:
        - set -e
        - npm run eslint
    - stage: test
      env:
        - LABEL: dockerlint
      script:
        - set -e
        - npm run dockerlint
    - stage: test
      env:
        - LABEL: mocha
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - set -e
        - npm run mocha
      after_script:
        - ./cc-test-reporter after-build -r "${CC_TOKEN}" --coverage-input-type lcov --exit-code ${TRAVIS_TEST_RESULT}
    - stage: release
      script:
        - set -e
        - git checkout ${TRAVIS_BRANCH};
        - COMMIT_MESSAGE=$(git log -n 1 --pretty=format:"%B");
        - |
          if [[ $COMMIT_MESSAGE == *"[major version bump]"* ]]; then
            ./scripts/versioning/iterate major -i -q;
          elif [[ $COMMIT_MESSAGE == *"[minor version bump]"* ]]; then
            ./scripts/versioning/iterate minor -i -q;
          else
            ./scripts/versioning/iterate -i -q;
          fi;
        - git push -q https://zephinzer:${GH_TOKEN}@github.com/zephinzer/anna.git --tags;
    - stage: publish
      script:
        - set -e
        - git checkout ${TRAVIS_BRANCH};
        - git fetch;
        - docker login -u "${DH_USERNAME}" -p "${DH_PASSWORD}"
        - CURRENT_VERSION=$(./scripts/versioning/get-latest -q)
        - TAG_LATEST="zephinzer/anna:latest"
        - TAG_VERSION="zephinzer/anna:${CURRENT_VERSION}"
        - npm run build -- development
        - docker push ${TAG_LATEST}-dev
        - docker tag ${TAG_LATEST}-dev ${TAG_VERSION}-dev
        - docker push ${TAG_VERSION}-dev
        - npm run build -- production
        - docker push ${TAG_LATEST}
        - docker tag ${TAG_LATEST} ${TAG_VERSION}
        - docker push ${TAG_VERSION}
        - docker logout
