version: "3"
services:
  application:
    build:
      context: ../
      dockerfile: ./provisioning/production.Dockerfile
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_SCHEMA: anna
      DB_USER: anna
      DB_PASSWORD: anna
      NODE_ENV: production
      PORT: 4000
    entrypoint: entrypoint: [ "./scripts/entrypoint.sh" ]
    expose:
      - "4000"
    ports:
      - "4000:4000"
    depends_on:
      - database_production
  database:
    image: mysql:5.7.20
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: anna
      MYSQL_USER: anna
      MYSQL_PASSWORD: anna
    expose:
      - "3306"
    ports:
      - "3307:3306"
    volumes:
      - "../data/db:/var/lib/mysql"
  migrate:
    build:
      context: ../
      dockerfile: ./provisioning/development.Dockerfile
    environment:
      DB_HOST: database
      DB_PORT: 3307
      DB_SCHEMA: anna
      DB_USER: anna
      DB_PASSWORD: anna
    entrypoint: [ "./scripts/migrate.sh" ]
  seed:
    build:
      context: ../
      dockerfile: ./provisioning/development.Dockerfile
    environment:
      DB_HOST: database
      DB_PORT: 3307
      DB_SCHEMA: anna
      DB_USER: anna
      DB_PASSWORD: anna
    entrypoint: [ "./scripts/seed.sh" ]
