version: "3"
services:
  mocha_test:
    build:
      context: ../
      dockerfile: ./provisioning/development.Dockerfile
    entrypoint: [ "npm", "run", "mocha" ]
    volumes:
      - '../coverage:/app/coverage'
  es_lint:
    build:
      context: ../
      dockerfile: ./provisioning/development.Dockerfile
    entrypoint: [ "npm", "run", "eslint" ]